"""create agent sessions

Revision ID: a52b03b185f8
Revises:
Create Date: 2026-08-24 16:42:34.060440

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a52b03b185f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("workspace_path", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_sessions_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_sessions_status"))

    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
