import { radii, spacing, typography } from "@ohmycode/design-tokens";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  brand: { alignItems: "center", flexDirection: "row", gap: spacing[3] },
  brandName: { fontSize: typography.body, fontWeight: "700", letterSpacing: -0.2 },
  context: { alignItems: "flex-end", bottom: 64, position: "absolute", right: 64 },
  contextBrand: { fontSize: 40, fontWeight: "800", letterSpacing: -1.6 },
  contextTagline: { fontSize: typography.body, marginTop: spacing[2] },
  controls: { alignItems: "center", borderRadius: radii.medium, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", padding: 3 },
  error: { borderRadius: radii.medium, borderWidth: StyleSheet.hairlineWidth, fontSize: typography.small, lineHeight: 18, paddingHorizontal: spacing[3], paddingVertical: 10 },
  eyebrow: { fontSize: typography.xs, fontWeight: "800", letterSpacing: 1.8 },
  form: { gap: 18 },
  formContainer: { maxWidth: 392, width: "100%" },
  heading: { marginBottom: 28 },
  panel: { borderRightWidth: StyleSheet.hairlineWidth, bottom: 0, left: 0, position: "absolute", top: 0, zIndex: 1 },
  panelContent: { flexGrow: 1, justifyContent: "center", paddingBottom: 64, paddingHorizontal: 64, paddingTop: 110 },
  panelContentRegister: { paddingBottom: spacing[8], paddingTop: 96 },
  panelNarrow: { borderRightWidth: 0, width: "100%" },
  panelWide: { width: 520 },
  screen: { flex: 1 },
  submit: { alignItems: "center", borderRadius: radii.medium, height: 48, justifyContent: "center", marginTop: spacing[2] },
  submitText: { fontSize: typography.body, fontWeight: "700" },
  subtitle: { fontSize: typography.body, lineHeight: 21, marginTop: 10 },
  switch: { alignItems: "center", marginTop: 18 },
  switchText: { fontSize: typography.small, textAlign: "center" },
  title: { fontSize: typography.authTitle, fontWeight: "700", letterSpacing: -1.2, lineHeight: 41, marginTop: 6 },
  topbar: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", left: 0, paddingBottom: spacing[3], paddingHorizontal: 28, paddingTop: 24, position: "absolute", top: 0, zIndex: 2 },
  topbarNarrow: { width: "100%" },
  topbarWide: { width: 520 },
});
